spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: service_customer
          uri: lb://DEMO-PROJECT
          order: 0
          predicates:
            - Path=/demo-project/**
          filters:
            - AddHeader=gaozhijun-request-header, Default-Bar
            - StripPrefix=1
      httpclient:
        pool:
          acquire-timeout: 10000
server:
  port: 8082
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8081/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug
    com.windmt.filter: debug



